travis:
  secure:
    BINSTAR_TOKEN: aymF0xzafQK0N+c8DAGrXa98OmAF8jkK21+fN8rKIw6h2znN3RSN7YygZd8r+k4eT85fgwU+YISLKp+B2oWNZg+BY+uQbtbjUKoTjAmAl160wVPTp+PsbU5wJn1vyk0ONafiaV10mDejn5HgoV+P5y7lGxYhE6qvIN6iB5zl9hjcU5f5IC2zTdqMh3c7HN11Q//sNP8KDcmaT5EXAyLb0GMKyxp2aJlRuc4wJMDwvNqVY0YZpgQEHTwAq9LToPB+2epI1Fgk20+vEsH1mOfdEvCjOr2X3L5lSv4qQDUo2ahWtf+XS7HZeCxZFZZpCqEDFl0y5iYeNI/i1FN9uzoDfiDo9HF8muMiJgT7uH/v1nTtpjtY0bTAsQucvAgCAzJZDS6p1JuZwIY9oWzm6QozBQ9B5vYUd7lQkJBMNYf5TjRbarawjGpacAOCjK+zKPas4WhyJPOC8p8wao/eLxCsmY+ajtnkpAfoOV1G3KfVWfqpvvm3wNEWg079mNmDEnXrjv+xxRK2ahVBY7MtpcHhFb0UN3DXcyl7yLAk28oHo+q1XBBzbJRYt+GsAalBCfF0dVZnmFha2nQ7LteukbmYbydiPTIMKwEVL5ogi1yhYVXIhrAuZYjEL0ZKMlGo9RLlA/GfjwMNtirnT8mWyWUDqHXEr9lWzXQNDUtBZ1KxzrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
